### ISSUE TITLE
ImageMagick error: Too many open files

### ISSUE THREAD

**Issue by Treeston** [freearhey/phash-js#2]
Calling `pHash.hash` repeatedly will eventually run into an ImageMagick `Error: Too many open files` error.

Minimal example:
```html
<!doctype html>
<html>
  <head>
    <script defer src="https://cdn.jsdelivr.net/npm/phash-js/dist/phash.js"></script>
    <script>
      document.addEventListener('DOMContentLoaded', async () =>
      {
        const file = new File(
         [Uint8Array.from(
          atob('iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAQAAAAAYLlVAAAAO0lEQVR42u3OMQEAAAwCIO0feovhAwloLlMVEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQWAce/hlAAXSB6WIAAAAASUVORK5CYII='),
          c => c.charCodeAt(0)
         )],
         '64x64.png',
         {type:'image/png'}
        );

        for (let i=1;;++i)
        {
          await pHash.hash(file);
          document.body.innerText = ('done '+i);
        }
      });
    </script>
  </head>
  <body></body>
</html>
```

This simply loads a 64x64 monocolor png into memory, then repeatedly hashes it. In both Firefox 90 and Chromium 80, this consistently fails on iteration 4094 (with `done 4093` as the last message shown). The error console shows a `Error: Too many open files` error raised by ImageMagick.

**Expected behavior:**
Being able to hash any number of files (sequentially) without needing to reload the page.

**Comment by freearhey** [comment]
This limitation comes from this [file](https://github.com/freearhey/phash-js/blob/v0.3.0/dist/magick.js) which is a direct copy of the file from the [wasm-imagemagick](https://www.npmjs.com/package/wasm-imagemagick) package. As soon as the author removes this restriction, I will bring these changes here as well.

**Comment by Treeston** [comment]
Have you reported this issue to the upstream?

**Comment by freearhey** [comment]
No, I didn't.
