### ISSUE TITLE
node JS realization

### ISSUE THREAD

**Issue by Fvh908** [freearhey/phash-js#3]
Hi your library works well, but I need to use it in node JS instead of browser.
I tried to rewrite it by reading the file from the computer, and passing it to the calculateHash method, skipping the resize method, because I will always have 32x32 pictures, but every time I get the error "Error: There is no data for a pixel at [0, 0 ] ".
I think you are doing image transformations in this method, can you help me with that?

My code - https://github.com/Fvh908/node-phash/tree/main/nodePhash

**Comment by freearhey** [comment]
Sorry, but I have no idea what the problem could be.
