### ISSUE TITLE
merge?

### ISSUE THREAD

**Issue by timhuff** [freearhey/phash-js#4]
Hey. I'm the author of `canvas-phash`. I haven't updated it in like 5 years but I'm doing so now. It hasn't had a dependency on canvas in all this time. I think it might satisfy your use case. Join forces?

**Comment by freearhey** [comment]
Honestly, I do not really understand how we can help each other here. Your library is designed for Node.js and I created this tool specifically for browsers and only to solve the problem of resizing images without using canvas. As for the algorithm itself, I'm fine with it.
